### ISSUE TITLE
Ya ni jala, khe verga???

### ISSUE THREAD

**Issue by carlosescom** [ChrisMHM/TT2_Node#6]
`npm start` ya no me funciona para levantar la app. Necesito tener la UX funcionando para replicarla en mi repo. Me lanza este error pero no cambié nada de ese archivo, no he cambiado nada que ver con Mongo y aún así crashea:
```bash
const droCollection = require('../db').db().collection('DRO');
                                      ^
TypeError: Cannot read property 'db' of null
```
Esta madre hasta les pudo haber fallado a medio TT 💣 

Yo creo que voy a guiarme por el documento de Word.

**Comment by ChrisMHM** [comment]
¿En qué momento deja de jalar?, supongo que es en el archivo del DRO.js pero estoy revisando y no tengo problema para correrlo.

**Comment by carlosescom** [comment]
De algun modo ya jala de nuevo... wtf
